[Issue #26][EC1337] Avoid unlimited cache
green-code-initiative/ecoCode-python pull request #27
Opened 2024-05-30 11:45 UTC by B3ND3L

New rule made during ecocode challenge 24

[EC1337] (random number between 1000 / 1500) to fix unlimited cache issue : https://github.com/green-code-initiative/ecoCode-python/issues/26

TEAM : TUNGSTEN

2024-06-02 21:34 UTC, dedece35 commented
Hi @B3ND3L, @Flow35650

please see my review feedback in PR https://github.com/green-code-initiative/ecoCode/pull/327

2024-06-03 17:12 UTC, B3ND3L commented
Hi @dedece35 


Before merge, there is the same typo as ecoCode PR.
I'll fix this right now.

2024-06-03 19:01 UTC, dedece35 requested changes
I've just released "ecocode-rules-specifications" with you ecocode PR included.
Please use now the "1.6.0" version of ecocode-rules-specification. Now, your Unit Tests will be OK.
Second modification, please, on test files ... please check screenshots where we can see our rule error, but also native Sonar error ... please correct this one in all lines with this error. This is to have a clean test file with only our rule errors.

2024-06-05 21:21 UTC, dedece35 approved these changes

2024-06-05 21:21 UTC, merged